### ISSUE TITLE
Bit widths for >32-bit registers when CSR width=32

### ISSUE THREAD

**Issue by bunnie** [litex-hub/lxsocdoc#7]
I've set CSR width to 32 bits and rebuilt documentation, and I see something like the attached image --

The text says "bits 0-31 of INFO_DNA_ID", but the register diagram makes it look like only bits 7-0 have been inferred...

![image](https://user-images.githubusercontent.com/1168375/73478845-ccb71d80-43d1-11ea-903f-a9c7e85a12dc.png)

**Comment by xobs** [comment]
It looks like betrusted-soc has its lxsocdoc dep pinned to 7a804486ff32b2094bda6c3cc7d3c331da5d1ff7

Can you try updating to e52e67cc8a3e321617d7c136a389c4dc85665d63 to see if that fixes it?

**Comment by bunnie** [comment]
Yep, that fixes it. thanks!
