### ISSUE TITLE
Where is lxsocdoc documentation now?

### ISSUE THREAD

**Issue by tcal-x** [litex-hub/lxsocdoc#8]
Hi, I found this, and I see there's documentation in older versions of the README about how to actually use it.   Did that documentation move to somewhere else?   It might be useful to have a link in the current README.

**Comment by enjoy-digital** [comment]
Hi @tcal-x, this can be found here: https://github.com/enjoy-digital/litex/wiki/SoC-Documentation.

**Comment by tcal-x** [comment]
Thanks!
